name: flutter_user_sdk
description: UserComSDK that simplify sending events and receiving campaign notifications
version: 1.1.0
homepage: https://github.com/UserEngage/Flutter-SDK

environment:
  sdk: ">=3.9.0 <5.0.0"
  flutter: " >=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^12.3.0
  dio: ^5.9.0
  advertising_id: ^2.7.1
  connectivity_plus: ^7.0.0
  hive: ^2.2.3
  path_provider: ^2.1.5
  another_flushbar: ^1.12.32
  url_launcher: ^6.3.2
  google_fonts: ^6.3.3

dev_dependencies:
  flutter_lints: ^6.0.0

